### ISSUE TITLE
MONGO ERROR

### ISSUE THREAD

**Issue by HotZeus** [KlanterV/chat-guard#1]
HER ŞEYİ DOĞRU YAPTIM AMA MONGO ERROR HATASI ALIYORUM ABİ NOLUR YARDIM ET NU BOTA İHTİYACIM VAR

**Comment by KlanterV** [comment]
ilk öncelikle caps kapa 2cil olarak o mongoerroru götüne sokarım 3cü olarak da moongose ile ilgili ve uyarı botunu engellemez
